// Research engine ideas. Written by Claude from the universe screen + web research.
// Keep old ideas and append new ones so the flagged-price log becomes a track record.
// Video links were chosen from titles and descriptions; Claude has not watched them.
window.HQ_IDEAS = {
  date: "2026-10-05",
  items: [
    {
      sym: "ADBE", code: "ADBE", name: "Adobe", market: "US", country: "US", sector: "Technology", t212: "ADBE_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-27", flaggedPrice: 235.47,
      thesis: "A 36% operating-margin, 41% free-cash-flow-margin software company priced at under 9× next year's earnings, the kind of multiple the market gives businesses it expects to shrink. Adobe is still growing about 11–12%.",
      whyCheap: "The market has decided generative AI (Midjourney, Sora, design tools from AI labs) will commoditise paid creative software. Add the announced departure of long-time CEO Shantanu Narayen and a broad de-rating of software multiples, and the stock is down about a third in a year despite beating guidance every quarter.",
      whyWrong: "The numbers haven't broken yet. Q3 FY26 (10 Sept) was a record and management raised digital-media growth guidance to 11.3%. AI-influenced recurring revenue passed $5B (from $3.5B at the start of the year) and Firefly app users grew 30% quarter on quarter. Professionals and enterprises pay for workflow, rights-cleared content and integration, not just image generation. At under 9× earnings the price assumes decline, so steady low-double-digit growth alone would be enough to re-rate it.",
      bear: "If AI turns 'good enough' creative work into a free feature, seat counts at small businesses and hobbyists could erode faster than enterprise gains replace them. Net new ARR already fell about 36% year on year in Q3 FY26 (management blames a deliberate freemium push). The incoming CEO comes from the marketing-software side, not the creative products.",
      watch: "Net new ARR each quarter and the FY27 ending-ARR guide in December; Firefly paid conversion.",
      catalysts: [
        { d: "1–2 Oct 2026", e: "Update: still near its 52-week low (about $238, down about 31% this year) after five straight earnings beats. DA Davidson kept its Buy and raised its target to $290, but the Street is mostly sceptical (23 Holds against 5 Sells). Firefly ARR grew 40% quarter on quarter", url: "https://247wallst.com/investing/2026/10/02/the-adobe-stock-debate-is-about-to-get-interesting/" },
        { d: "28–30 Oct 2026", e: "Adobe MAX: new Firefly models, agents and pricing aimed at converting 100M+ free creative users", url: "https://convcast.com/event/adobe-max-2026/" },
        { d: "1 Dec 2026", e: "Anil Chakravarthy (internal, announced 2 Sept) becomes CEO; Narayen moves to Executive Chair", url: "https://news.adobe.com/news/2026/09/adobe-announces-anil-chakravarthy-to-become-president-and-ceo" },
        { d: "Dec 2026", e: "Q4 FY26 results and FY27 guidance: first full-year outlook since the AI panic", url: "https://www.ad-hoc-news.de/boerse/news/corporate-news/adobe-inc-stock-dips-after-record-q3-fy2026-results-and-raised-guidance/70084138" },
        { d: "Ongoing", e: "AI-influenced ARR above $5B: the metric that tests whether AI is adding to Adobe or replacing it", url: "https://www.fool.com/investing/2026/09/08/adobes-next-earnings-report-on-sept-10-could-send-the-stock-plunging-heres-why/" }
      ],
      videos: [["Adobe Just Proved the AI Bears Wrong: Q2 FY26 analysis", "https://www.youtube.com/watch?v=aiW4Dibt7oQ"], ["Adobe SWOT 2026: CEO exit, Firefly AI", "https://www.youtube.com/watch?v=FPvlHkV7Ldk"]],
      sources: [["Motley Fool: Adobe's Sept 10 report", "https://www.fool.com/investing/2026/09/08/adobes-next-earnings-report-on-sept-10-could-send-the-stock-plunging-heres-why/"], ["Leverage Shares: down 40% on AI fears", "https://leverageshares.com/us/insights/down-40-on-ai-fears-can-adobe-stock-recover/"], ["Record Q3 FY26 and raised guidance", "https://www.ad-hoc-news.de/boerse/news/corporate-news/adobe-inc-stock-dips-after-record-q3-fy2026-results-and-raised-guidance/70084138"]]
    },
    {
      sym: "INTU", code: "INTU", name: "Intuit", market: "US", country: "US", sector: "Technology", t212: "INTU_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-27", flaggedPrice: 275.79,
      thesis: "TurboTax, QuickBooks and Credit Karma at 11.5× forward earnings after a 60% fall, with management still committed to at least high-teens EPS growth. The market is pricing a disruption that hasn't shown up in the profit line.",
      whyCheap: "Investors fear AI agents will do people's taxes and bookkeeping for free. The September 17 Investor Day didn't calm that: fiscal 2027 revenue guidance of 9–10% (down from 14%), TurboTax growth of just 2–3%, Mailchimp flat, and management admitted TurboTax lost about 3 points of DIY market share on pricing. Shares fell another 13% after the event.",
      whyWrong: "The slowdown is concentrated in two mature products (DIY tax and Mailchimp). QuickBooks and the mid-market business platform, plus TurboTax Live (humans plus AI for assisted tax), are the growth engines, and Intuit holds the tax and ledger data that any AI agent would need. Margins are improving (operating margin up about 9 points year on year in the latest quarters) and management says it's committed to high-teens EPS growth. At 11.5× earnings that growth is barely priced.",
      bear: "If AI tax agents (from Big Tech or startups) win the simple-return market, TurboTax's highest-margin customers go first. Losing 3 points of DIY share in a year shows real price sensitivity. A second weak tax season would confirm the structural-decline story.",
      watch: "The 2027 tax season (Jan–Apr): TurboTax unit share, and whether Live keeps growing faster than DIY shrinks.",
      catalysts: [
        { d: "1–2 Oct 2026", e: "Update: down about 18% over the past month. Traders bought unusually heavy call options on 1 Oct (volume over 2.5× normal), betting on a rebound. The average analyst target (about $432) is roughly 50% above the price", url: "https://247wallst.com/investing/2026/10/02/intuit-wasnt-on-cramers-muse-casualty-list-and-traders-just-piled-into-its-october-calls/" },
        { d: "29 Sept 2026", e: "Update: QuickBooks is now a connector inside Meta's Muse for Small Business AI agent (invoices, cash flow, revenue analysis). Intuit becomes a data layer for AI agents rather than being bypassed, but it also puts Meta between Intuit and its customers. INTU fell about 1.5% on the day", url: "https://www.pymnts.com/partnerships/2026/meta-and-intuit-team-on-small-business-intelligence/" },
        { d: "Late Nov 2026", e: "Q1 FY27 results: first quarter after the reset guidance", url: "https://www.quiverquant.com/news/Intuit+Falls+as+Investor+Day+Reaffirmed+a+Slower+Growth+Outlook" },
        { d: "Jan–Apr 2027", e: "US tax season: the real test of TurboTax share vs AI tools", url: "https://finance.yahoo.com/markets/stocks/articles/intuit-crashed-over-agentic-ai-132427512.html" },
        { d: "Ongoing", e: "Mid-market QuickBooks/ERP push: the part of the business still growing fast", url: "https://www.youtube.com/watch?v=Amr7cpWZfg4" }
      ],
      videos: [["Intuit Investor Day 2026: full presentation", "https://www.youtube.com/watch?v=Amr7cpWZfg4"], ["Intuit Investor Day 2026: CTO on the AI platform", "https://www.youtube.com/watch?v=0HYjguIxwy0"]],
      sources: [["Yahoo: crashed over agentic AI fears", "https://finance.yahoo.com/markets/stocks/articles/intuit-crashed-over-agentic-ai-132427512.html"], ["Quiver: Investor Day reaffirmed slower growth", "https://www.quiverquant.com/news/Intuit+Falls+as+Investor+Day+Reaffirmed+a+Slower+Growth+Outlook"], ["Librarian Capital: still in free fall after Investor Day", "https://librariancapital.substack.com/p/intuit-still-in-free-fall-after-investor"]]
    },
    {
      sym: "DECK", code: "DECK", name: "Deckers Brands (HOKA, UGG)", market: "US", country: "US", sector: "Consumer Discretionary", t212: "DECK_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-27", flaggedPrice: 78.67,
      thesis: "Record revenue, a raised profit outlook, $1.1B cash with no net debt and heavy buybacks, at about 10× forward earnings: roughly the multiple of a no-growth retailer. The market still prices HOKA as a fad that has peaked.",
      whyCheap: "HOKA's growth slowed sharply from its 20%+ glory years, new US footwear tariffs dented margins (about $150M of cost), and a soft outlook last October knocked the stock 15%. BMO started coverage at Underperform in September. With 7% of shares sold short, the story is 'the running-shoe boom is over'.",
      whyWrong: "The latest numbers point to a slowdown, not a collapse. Q1 FY27 (July) was the first $1B+ first quarter ever, HOKA grew 7.7% and UGG 4.9%, and the full-year EPS outlook was raised to $7.35–7.50 on high-single-digit sales growth. Return on capital is around 90%. Deckers bought back $1.1B of stock last year and $338M in Q1 alone, shrinking the share count at a very low price. Paying 10× earnings for a business still growing and still this profitable prices in a decline that isn't happening.",
      bear: "Footwear brands can fade fast (Crocs and Under Armour have both done it). If HOKA growth turns negative as competitors (On, Nike's running reboot) catch up, or tariffs escalate further, earnings could fall and 10× wouldn't be cheap. UGG is seasonal and fashion-dependent.",
      watch: "HOKA growth rate each quarter (low double digits vs mid single digits) and gross margin after tariffs.",
      catalysts: [
        { d: "22 Oct 2026", e: "Q2 FY27 results: first look at HOKA's autumn and the holiday outlook. Consensus EPS is $1.82, flat on a year ago, so the bar is low. The average analyst target (about $114) is about 45% above the price. No new company news since it was flagged", url: "https://www.ad-hoc-news.de/boerse/news/corporate-news/deckers-outdoor-stock-fell-0-57-percent-on-october-2-2026/70223740" },
        { d: "Nov–Dec 2026", e: "UGG holiday season, the brand's biggest quarter; new 'Born to Feel' campaign", url: "https://www.businesswire.com/news/home/20260922856973/en/UGG%C2%AE-Launches-Invi" },
        { d: "Ongoing", e: "Buybacks: $338M in Q1 alone shrinks the share count at around 10× earnings", url: "https://www.nasdaq.com/press-release/deckers-brands-reports-first-quarter-fiscal-year-2027-financial-results-2026-07-23" }
      ],
      videos: [["Deckers Q4 FY26 earnings call: HOKA and UGG demand", "https://www.youtube.com/watch?v=F0sSP_bMJyA"], ["Deckers Brands: FY26 earnings analysis", "https://www.youtube.com/watch?v=_fFpx3G_3xM"]],
      sources: [["Deckers Q1 FY27 results", "https://ir.deckers.com/news-events/press-releases/detail/661/deckers-brands-reports-first-quarter-fiscal-year-2027-financial-results"], ["CNBC: stock sinks on soft outlook (Oct 2025)", "https://www.cnbc.com/2025/10/24/deckers-stock-deck-hoka-ugg.html"], ["WWD: Q1 FY27 'strong start'", "https://wwd.com/footwear-news/shoe-industry-news/deckers-brands-deck-q1-2027-earnings-hoka-ugg-1239081054/"]]
    },
    {
      sym: "ams/ADYEN", code: "ADYEN", name: "Adyen", market: "Europe", country: "Netherlands", sector: "Technology", t212: "ADYENa_EQ", ccy: "EUR",
      flaggedDate: "2026-09-27", flaggedPrice: 875.5,
      thesis: "Europe's best payments platform, growing net revenue in the low 20s% with €12B of net cash and 46% operating margins, down 37% in a year on a guidance miss of roughly one percentage point.",
      whyCheap: "In February Adyen guided 2026 net revenue growth to 20–22%, a touch below the roughly 23% analysts wanted, and payment volumes came in slightly light. The stock fell as much as 20% in a day and has never recovered. Payments stocks broadly are out of favour on fears of stablecoins, Big Tech wallets and price competition.",
      whyWrong: "The business delivered. H1 2026 net revenue rose 21% in constant currency, EBITDA grew 18%, and management raised full-year guidance to 21–23%. It's also expanding beyond processing into loyalty, billing and money movement, recently joined Guidewire's insurance marketplace, and plans an India expansion. A forward P/E around 20× is barely above the European tech median for a company growing at twice the rate, with a fortress balance sheet.",
      bear: "Adyen's growth depends on large merchants moving more volume to it. A consumer slowdown or a big client leaving would hit quickly, and competition from Stripe and PayPal's enterprise push could squeeze the take rate. The stock has been volatile around every update: another small miss could mean another 20% day.",
      watch: "Net revenue growth vs the 21–23% guide, and the take rate.",
      catalysts: [
        { d: "Early Oct 2026", e: "Update: down about 15% in the past 30 days and about 39% this year. Shareholders meet at an extraordinary general meeting on 7 Oct; Klarna's Niclas Neglen joins as CFO on 1 Feb 2027, subject to approvals", url: "https://www.ad-hoc-news.de/boerse/news/corporate-news/adyen-stock-gets-a-new-cfo-ahead-of-october-results/70228425" },
        { d: "28 Oct 2026", e: "Q3 business update: first check against the raised guidance", url: "https://www.adyen.com/press-and-media/adyen-publishes-h1-2026-financial-results-3wjne" },
        { d: "2026–27", e: "New CFO from Klarna (Niclas Neglen): watch for any change to capital return, since €12B of cash sits unused", url: "https://www.pymnts.com/personnel/2026/adyen-names-klarna-cfo-niclas-neglen-new-f" },
        { d: "Ongoing", e: "India expansion and Guidewire insurance-payments partnership: new volume beyond retail", url: "https://www.prnewswire.com/news-releases/adyen-joins-guidewire-marketplace-as-an" }
      ],
      videos: [["Adyen after 1H26 earnings: DCF and fair value", "https://www.youtube.com/watch?v=72QxWaYkeUk"], ["Adyen soars on results: Bloomberg Stock Movers", "https://www.youtube.com/watch?v=Mdz6DD2wCms"]],
      sources: [["Adyen H1 2026 results", "https://www.adyen.com/press-and-media/adyen-publishes-h1-2026-financial-results-3wjne"], ["CNBC: shares plummet on weak outlook (Feb 2026)", "https://www.cnbc.com/2026/02/12/adyen-stock-price-earnings.html"], ["Investing.com: H1 2026 call transcript", "https://www.investing.com/news/transcripts/earnings-call-transcript-adyen-shares-jump-on-h1-2026-growth-platform-push-93CH-4858426"]]
    },
    {
      sym: "KSPI", code: "KSPI", name: "Kaspi.kz", market: "US", country: "US (Kazakhstan company)", sector: "Technology", t212: "KSPI_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-27", flaggedPrice: 95.67,
      thesis: "One of the most profitable fintechs in the world (54% operating margin, 82% return on capital), used by about 15 of Kazakhstan's 19 million people, priced at under 7× forward earnings with a dividend yield of roughly 6–9% (sources differ because some payouts are one-offs).",
      whyCheap: "Geography, not business quality. Investors apply a heavy discount for Kazakhstan (politics, currency, closeness to Russia), and the expansion into Turkey via Hepsiburada is currently losing money: its quarterly EBITDA fell 76% and losses widened. Kaspi's Q2 2026 net income was flat as Turkish investment and high Kazakh funding costs absorbed growth.",
      whyWrong: "The home business is a near-monopoly super-app (payments, shopping, lending and savings in one) still growing revenue about 15% in 2026, and it pays out most of its profit. Turkey is a much larger market; Kaspi bought a bank there (now Hepsi Bank) to repeat its proven playbook of shopping plus financing. If Turkey even partly works, today's price treats that option as worthless. Mohnish Pabrai, a well-known value investor, has publicly explained owning it.",
      bear: "Political or regulatory risk in Kazakhstan is real and can't be diversified inside one stock. The tenge can drop, which cuts dollar dividends. Turkey could become a cash drain for years, in a hyperinflationary economy. As a US-listed ADR it trades in USD on Trading 212, so there's a currency conversion fee.",
      watch: "Hepsiburada losses narrowing, and Kazakh payment volumes.",
      catalysts: [
        { d: "Late Oct–mid Nov 2026", e: "Q3 2026 results: Turkey losses and dividend declaration. The date isn't announced yet (Q3 2025 came on 10 Nov, Q3 2024 on 21 Oct). No major company news since it was flagged", url: "https://www.globenewswire.com/news-release/2025/10/08/3163210/0/en/Kaspi-kz-to-Announce-3rd-Quarter-9-months-2025-Financial-Results-on-10th-November.html" },
        { d: "2026–27", e: "Hepsi Bank (ex-Rabobank Türkiye) rollout of shopping loans inside Hepsiburada", url: "https://fbroker.kz/en/analytics/analytics-article/kaspikz-q2-2026-results-en-2" },
        { d: "Quarterly", e: "Dividend: roughly 6–9% yield at today's price depending on the source; Q2's payout was 18% higher than Q1's", url: "https://www.investing.com/news/transcripts/earnings-call-transcript-kaspikz-posts-strong-q2-2026-growth-shares-rise-34-93CH-4849353" }
      ],
      videos: [["Kaspi.kz: the Kazakh super-app (Business Breakdowns)", "https://www.youtube.com/watch?v=wDtXE7lowH8"], ["Why I'm buying Kaspi: Mohnish Pabrai explains", "https://www.youtube.com/watch?v=0LO5SeyhFGY"]],
      sources: [["Kaspi.kz Q2 & 1H 2026 results", "https://www.globenewswire.com/news-release/2026/08/10/3341673/0/en/kaspi-kz-2q-1h-2026-financial-results.html"], ["Freedom Broker: Q2 2026 analysis", "https://fbroker.kz/en/analytics/analytics-article/kaspikz-q2-2026-results-en-2"], ["Seeking Alpha: proven playbook in a larger market", "https://seekingalpha.com/article/4933853-kaspikz-betting-on-a-proven-playbook-in-a-much-larger-market"]]
    },
    {
      sym: "lon/GSK", code: "GSK", name: "GSK", market: "UK", country: "UK", sector: "Healthcare", t212: "GSKl_EQ", ccy: "GBX",
      flaggedDate: "2026-09-27", flaggedPrice: 1851,
      thesis: "A UK pharma giant at about 10× forward earnings, against around 16× for European healthcare, with a near-4% dividend, a new CEO buying growth, and a pipeline delivering approvals. You can buy it in pounds on the London line, with no FX fee.",
      whyCheap: "The patent cliff. Dolutegravir, the backbone of GSK's HIV business and almost 20% of sales, loses US protection in April 2028 and Europe in 2029. Investors doubt GSK can replace that profit, remember years of underperformance under the previous CEO, and see the $10.6B Nuvalent deal (for a company with no revenue) as expensive. Analysts sit at Hold.",
      whyWrong: "The replacement pipeline is arriving early. Nuvalent's zidesamtinib (Jideytro) won US approval in July, ahead of its September target; neladalkib has an FDA decision due 27 November; and Japan approved bepirovirsen as the first functional cure for chronic hepatitis B. New CEO Luke Miels is targeting £40B of revenue by 2031 with £1.9B of annual cost savings by 2029, and his first results showed core operating profit up 11%. At 10× earnings, the cliff looks priced in and the pipeline doesn't.",
      bear: "Patent cliffs are brutal. If HIV sales drop faster than new drugs ramp, earnings could fall in 2028–30 and a dividend cut becomes possible. Big acquisitions often destroy value. GSK has about £15B of net debt, and US drug-pricing pressure hits every pharma company.",
      watch: "Neladalkib FDA decision (27 Nov) and new-product sales growth vs HIV decline.",
      catalysts: [
        { d: "Early Oct 2026", e: "Update: GSK agreed to buy a multiple myeloma drug programme (a trispecific T-cell engager) from ChImagen Biosciences for up to $750M including milestones, with Phase 1 trials planned for 2027. It's small next to Nuvalent but adds to the oncology push. Shares are about 4% below the flagged price", url: "https://foreignpolicyjournal.com/2026/10/04/gsk-nyse-gsk-strikes-750-million-deal-to-acquire-trispecific-t-cell-engager-from-chimagen-biosciences-for-multiple-myeloma" },
        { d: "28 Oct 2026", e: "Q3 2026 results: progress on the £1.9B savings plan", url: "https://qz.com/gsk-cost-savings-program-drug-pipeline-q2-earnings-072826" },
        { d: "27 Nov 2026", e: "FDA decision on neladalkib (ALK lung cancer), the second Nuvalent drug", url: "https://www.fiercepharma.com/pharma/gsk-secures-first-ever-lung-cancer-fda-approval-jideytro-nuvalent-deal" },
        { d: "2026–27", e: "Bepirovirsen hepatitis B launches beyond Japan: potential multi-billion market", url: "https://www.youtube.com/watch?v=k4x2o_CbkRc" },
        { d: "Apr 2028", e: "Dolutegravir US patent expiry: the risk everyone is pricing", url: "https://pharmaboardroom.com/articles/gsks-luke-miels-bets-big-on-oncology-can-growth-outpace-the-patent-cliff/" }
      ],
      videos: [["GSK after the $10.6B Nuvalent deal (2026 analysis)", "https://www.youtube.com/watch?v=k4x2o_CbkRc"], ["Luke Miels appointed CEO: Reuters", "https://www.youtube.com/watch?v=lmK8-wniqlo"]],
      sources: [["GSK: Jideytro approved in the US", "https://www.gsk.com/en-gb/media/press-releases/jideytro-zidesamtinib-approved-in-the-us-for-previously-treated-ros1-positive-non-small-cell-lung-cancer/"], ["PharmaBoardroom: can growth outpace the patent cliff?", "https://pharmaboardroom.com/articles/gsks-luke-miels-bets-big-on-oncology-can-growth-outpace-the-patent-cliff/"], ["US News: $10.6B Nuvalent takeover", "https://www.usnews.com/news/top-news/articles/2026-06-09/uks-gsk-to-buy-us-based-cancer-drugmaker-nuvalent-for-10-6-billion"]]
    },
    {
      sym: "EVR", code: "EVR", name: "Evercore", market: "US", country: "US", sector: "Financials", t212: "EVR_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-27", flaggedPrice: 262.91,
      thesis: "The highest HQ Score among the ignored gems (90): a pure M&A-advisory bank with revenue up about 45% over the past year, net cash and 35% free-cash-flow margins, down 23% because investors think the deal cycle has peaked.",
      whyCheap: "Evercore earns over 80% of revenue from advising on deals, so the stock trades on the M&A cycle. After a huge Q1, Q2 beat only modestly and management said Q3 capital-markets activity was tracking below expectations. With the Fed hiking and rate-hike odds rising, the market is pricing a deal slowdown.",
      whyWrong: "Advisory is lumpy quarter to quarter, but the multi-year drivers are intact: record corporate cash, private equity sitting on unspent capital that must be invested, and a consolidation wave (the 'M&A renaissance'). Evercore keeps taking share from big banks by hiring senior bankers. Analysts' median target is about 43% above today's price. At around 14× forward earnings with 25%+ expected growth, a slow quarter looks priced in.",
      bear: "If rate hikes continue and markets wobble, CEOs postpone deals and advisory revenue can fall 20–30% in a year. Pay is the big cost, so profits fall faster than revenue. This is a cyclical stock, not a compounder, and it would add financial-cycle risk to a portfolio that has none today.",
      watch: "Q3 advisory revenue and backlog commentary (28 Oct); overall announced M&A volumes. Screen status 5 Oct: no longer passes the full gem test, because its value gap slipped to 58 (cut-off 60) as sector peers got cheaper. Still the highest-quality name here (HQ 90).",
      catalysts: [
        { d: "1 Oct 2026", e: "Update: Goldman Sachs kept its Buy but cut its target to $331 from $377. Friday's weak jobs data cut Fed hike odds to about 16%, which helps the deal backdrop. Evercore also advised Copart on its $1.9B ACV deal", url: "https://www.ad-hoc-news.de/boerse/news/nebenwerte/goldman-sachs-cuts-target-for-evercore-stock-to-usd-331/70216526" },
        { d: "28 Oct 2026", e: "Q3 2026 results: management guided below consensus, so the bar is low", url: "https://finance.yahoo.com/markets/stocks/articles/evercore-expects-softer-third-quarter-142327599.html" },
        { d: "27–28 Oct 2026", e: "Fed meeting: another hike would delay deals; a pause helps", url: "https://www.cnbc.com/2026/09/23/market-sees-next-fed-hike-in-october-following-barr-comments-hot-inflation.html" },
        { d: "2026–27", e: "M&A 'renaissance': mega-deals and private-equity dry powder", url: "https://www.youtube.com/watch?v=7_iHcsQO8aw" }
      ],
      videos: [["Evercore Q1 2026 earnings call", "https://www.youtube.com/watch?v=1KukptJYQSA"], ["WSJ: the 2026 M&A renaissance", "https://www.youtube.com/watch?v=7_iHcsQO8aw"]],
      sources: [["Investing.com: Q2 2026 call transcript", "https://www.investing.com/news/transcripts/earnings-call-transcript-evercore-beats-q2-2026-estimates-as-stock-falls-premarket-93CH-4820439"], ["Yahoo: Evercore expects softer Q3", "https://finance.yahoo.com/markets/stocks/articles/evercore-expects-softer-third-quarter-142327599.html"], ["Quiver: why EVR is down", "https://www.quiverquant.com/news/Why+Evercore+(EVR)+Stock+Is+Down+Today"]]
    },
    {
      sym: "ZTO", code: "ZTO", name: "ZTO Express", market: "US", country: "US (China company)", sector: "Industrials", t212: "ZTO_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-30", flaggedPrice: 19.6,
      thesis: "China's largest parcel carrier (about 20% of all Chinese parcels) with profit up 57% last quarter, priced at 9.5× forward earnings against about 23× for industrials, and committed to returning at least half its profit through dividends and buybacks.",
      whyCheap: "Two things: the China discount (investors avoid Chinese stocks on geopolitics, delisting and economic worries) and slowing parcel growth. In August ZTO cut its 2026 volume guidance to 6–10% growth (40.8–42.4 billion parcels) as industry-wide growth slowed, and the sector has a long history of brutal price wars.",
      whyWrong: "Profit is growing much faster than volume because the price war is easing. Beijing's 'anti-involution' campaign (a push against destructive underpricing) has brought regional price floors for parcels, and ZTO's Q2 2026 unit price rose 15.5%. Revenue grew 23%, net income 57% to RMB3.1B, and market share still edged up to 19.9%. It bought back $740M of stock in H1 2026 under a $1.5B programme, plus a 3–4% dividend. At 9.5× earnings the market is pricing the old price-war economics, not the new ones.",
      bear: "If Beijing relaxes the anti-involution push, or a rival (J&T, YTO, JD) restarts price cuts, the unit-price gains could reverse fast. Chinese e-commerce growth is maturing. As a Chinese ADR there's delisting and geopolitical risk you can't diversify away, and US–China tensions can hit the share price regardless of results. It trades in USD on Trading 212, so there's an FX fee.",
      watch: "Unit price per parcel vs volume growth each quarter: rising price with steady share means the price war is really over.",
      catalysts: [
        { d: "21 Sept–2 Oct 2026", e: "Update: Alibaba was reported buying about 46.9M ZTO shares at $19.45 on 21 Sept, close to today's price, and ZTO kept buying back its own stock (378,600 shares for $7.4M on 2 Oct). JPMorgan has downgraded it to Neutral ($29 target)", url: "https://www.gurufocus.com/news/9100795/alibaba-group-holding-ltd-buys-zto-express-cayman-inc-zto-shares-look-30-undervalued-on-gf-value" },
        { d: "11 Nov 2026", e: "Singles' Day: China's biggest parcel-volume event of the year", url: "https://olachina.org/singles-day-2026/" },
        { d: "Mid–late Nov 2026", e: "Q3 2026 results (date not yet announced): unit price and full-year volume guide", url: "https://zto.investorroom.com/2026-08-18-ZTO-Reports-Second-Quarter-2026-Unaudited-Financial-Results" },
        { d: "Mar 2026–Mar 2028", e: "$1.5B buyback programme, $740M used by end of June; target of 50%+ of adjusted profit returned each year", url: "https://www.nasdaq.com/press-release/zto-reports-second-quarter-2026-unaudited-financial-results-2026-08-18" },
        { d: "Ongoing", e: "Anti-involution parcel price floors (e.g. Yiwu raised its minimum from 1.1 to 1.2 yuan)", url: "https://thebambooworks.com/is-chinas-express-delivery-price-war-over-the-answer-will-lie-in-profits/" }
      ],
      videos: [["ZTO Express stock analysis: Chinese growth", "https://www.youtube.com/watch?v=9xScFzC5vUo"]],
      sources: [["ZTO Q2 2026 results", "https://zto.investorroom.com/2026-08-18-ZTO-Reports-Second-Quarter-2026-Unaudited-Financial-Results"], ["Yahoo: ZTO Q2 earnings and revenues rise", "https://finance.yahoo.com/markets/stocks/articles/zto-express-q2-earnings-revenues-171900344.html"], ["The Bamboo Works: ZTO lowers volume guidance", "https://thebambooworks.com/zto-lowers-annual-parcel-volume-guidance-as-industry-growth-slows/"]]
    },
    {
      sym: "BKNG", code: "BKNG", name: "Booking Holdings", market: "US", country: "US", sector: "Consumer Discretionary", t212: "PCLN_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-30", flaggedPrice: 162.34,
      thesis: "The world's biggest online travel company (Booking.com, Priceline, Agoda, Kayak) with a 36% EBITDA margin and around 90% return on capital, down 27% in a year to about 14.6× forward earnings because investors think AI agents will book travel for people instead.",
      whyCheap: "AI disintermediation fear. Meta's Muse agent became the most-downloaded app in September, and on 22 Sept Expedia joined it so users can book trips without visiting Expedia or Booking. Booking fell again the next day. Growth also slowed: room nights grew 5% in Q2 2026 against 9% in Q4 2025 because the Middle East conflict hit long-haul travel. In May it cut full-year guidance and faces EU regulatory scrutiny.",
      whyWrong: "An AI agent still needs hotel supply, prices, payments and customer service, and Booking has the largest direct hotel network in the world. Morgan Stanley argues AI is a new acquisition channel for travel platforms rather than a replacement. The business is still growing: Q2 revenue +8%, gross bookings +9%, and a record $4.1B returned in one quarter ($3.7B of buybacks), cutting the share count 6% in a year. Management expects low-to-mid-teens EPS growth in 2026, which 14.6× doesn't pay much for. (The low share price is due to a 25-for-1 split on 2 April 2026.)",
      bear: "If AI agents become where travel is searched, Booking may have to pay them for traffic, like it pays Google today, and margins would fall. Expedia moved first with Meta. Travel is cyclical and exposed to geopolitics and oil prices. Booking also has more debt than it used to after issuing bonds this year. This overlaps with Amadeus below: both are bets that AI fears in travel are overdone.",
      watch: "Room-night growth and marketing spend as a share of revenue: rising spend would suggest AI is raising the cost of getting customers.",
      catalysts: [
        { d: "1–2 Oct 2026", e: "Update: Booking and Expedia took opposite bets. Expedia joined Meta's Muse agent and Booking stayed out. Booking's CFO says AI chatbots still send it under 1% of room nights, and its direct-booking share holds in the mid-60s%. Truist cut targets on both after Muse reached 560,000 daily users in 11 days", url: "https://247wallst.com/investing/2026/10/01/how-booking-holdings-and-expedia-are-taking-opposite-bets-on-ai-shopping-agents/" },
        { d: "~27 Oct 2026", e: "Q3 2026 results (estimated date): summer travel and any comment on AI-agent partnerships", url: "https://www.marketbeat.com/stocks/NASDAQ/BKNG/earnings/" },
        { d: "2026–27", e: "Transformation programme: expected annual savings raised to $650M, mostly landing in 2027", url: "https://www.investing.com/news/company-news/booking-holdings-q2-2026-slides-record-capital-return-growth-slows-93CH-4836178" },
        { d: "Ongoing", e: "AI-agent deals: watch whether Booking signs with Meta Muse or other agents as Expedia has", url: "https://www.fool.com/investing/2026/09/23/why-booking-holdings-stock-was-sliding-today/" }
      ],
      videos: [["Booking Holdings: replaced by AI or buying opportunity?", "https://www.youtube.com/watch?v=ELI4CGNY-SY"], ["Booking Holdings CEO on AI bets and navigating uncertainty", "https://www.youtube.com/watch?v=KKw81flgPnw"]],
      sources: [["Investing.com: Q2 2026 slides, record capital return", "https://www.investing.com/news/company-news/booking-holdings-q2-2026-slides-record-capital-return-growth-slows-93CH-4836178"], ["Motley Fool: why Booking was sliding (23 Sept)", "https://www.fool.com/investing/2026/09/23/why-booking-holdings-stock-was-sliding-today/"], ["Yahoo: Morgan Stanley dismisses AI threat", "https://finance.yahoo.com/markets/stocks/articles/booking-holdings-stock-falls-morgan-085827793.html"], ["SEC: Q2 2026 earnings release", "https://www.sec.gov/Archives/edgar/data/0001075531/000107553126000036/q2-26bkngearningsrelease.htm"]]
    },
    {
      sym: "NBIX", code: "NBIX", name: "Neurocrine Biosciences", market: "US", country: "US", sector: "Healthcare", t212: "NBIX_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-30", flaggedPrice: 138.35,
      thesis: "A neuroscience drugmaker that just passed $1B of quarterly revenue (+39% a year), with no debt and three growing drugs, priced at about 12× forward earnings against 18× for healthcare. Its HQ Score is 82, the highest among the new ideas.",
      whyCheap: "Worries about its biggest drug. Ingrezza (tardive dyskinesia, about three-quarters of sales) faces a rival, Teva's Austedo, whose Medicare-negotiated lower price starts in 2027. That could force Ingrezza's price down or cost it insurance coverage. A bigger Medicare Part D rebate from 2027 means roughly a 3% net price hit. The shares fell about 12% in a month after Q2 despite a guidance raise, partly on safety questions about the newly acquired Prader-Willi drug Vykat XR.",
      whyWrong: "Volume is doing the work: Ingrezza prescriptions are growing about 17% a year, only around 10% of US tardive dyskinesia patients are treated, and guidance was raised to $2.825–2.875B. Crenessity (a rare adrenal disorder) reached a $750M annual run rate about a year after approval, already above earlier peak-sales estimates. Management says the company is 'treated like a value company' while growing like a growth company. At 12× earnings, the pricing risk looks more than priced in.",
      bear: "Drug companies with one dominant product are fragile. If 2027 Medicare dynamics hit Ingrezza harder than the 3% management expects, earnings could stall. Ingrezza's small-biotech exemption from direct Medicare negotiation only lasts until 2027 (for 2029 prices). Two big Phase 3 trials (depression and schizophrenia) read out in 2027–28 and could fail. It adds healthcare, a sector you don't own today, so it would diversify you but in an area that's hard to judge.",
      watch: "Ingrezza volume vs net price in 2027 guidance (given in February), and Crenessity's run rate. Screen status 5 Oct: no longer passes the 'out of favour' test, because it's up about 4.5% on the year and rated Strong Buy. The business case is unchanged; it's just less of a contrarian idea now.",
      catalysts: [
        { d: "Early Oct 2026", e: "Update: up about 3.5% since flagged. No new company news; the CFO sold about $363K of stock (small, and common for executives paid in shares)", url: "https://www.marketbeat.com/stocks/NASDAQ/NBIX/news/" },
        { d: "~28 Oct 2026", e: "Q3 2026 results (estimated date; not yet confirmed by the company)", url: "https://www.biospace.com/press-releases/neurocrine-biosciences-reports-second-quarter-2026-financial-results" },
        { d: "Q4 2026", e: "R&D webinar on the early neurology and immunology pipeline", url: "https://www.investing.com/news/transcripts/neurocrine-biosciences-at-wells-fargo-conference-growth-story-broadens-93CH-4894418" },
        { d: "Jan 2027", e: "Medicare Part D changes and Austedo's negotiated price take effect: the key test for Ingrezza pricing", url: "https://finance.yahoo.com/markets/stocks/articles/nbix-stock-dips-12-month-143900602.html" },
        { d: "2027–28", e: "Phase 3 data for osavampator (depression) and a muscarinic drug for schizophrenia", url: "https://www.investing.com/news/transcripts/neurocrine-biosciences-at-wells-fargo-conference-growth-story-broadens-93CH-4894418" }
      ],
      videos: [["Neurocrine Q1 2026 earnings conference call", "https://www.youtube.com/watch?v=fKiIyHhykg4"]],
      sources: [["Neurocrine Q2 2026 results", "https://www.biospace.com/press-releases/neurocrine-biosciences-reports-second-quarter-2026-financial-results"], ["Investing.com: Wells Fargo conference, growth story broadens", "https://www.investing.com/news/transcripts/neurocrine-biosciences-at-wells-fargo-conference-growth-story-broadens-93CH-4894418"], ["Yahoo/Zacks: NBIX dips 12% in a month", "https://finance.yahoo.com/markets/stocks/articles/nbix-stock-dips-12-month-143900602.html"], ["Seeking Alpha: Ingrezza guidance raised", "https://seekingalpha.com/news/4622322-neurocrine-raises-2026-ingrezza-sales-guidance-to-2_825b-2_875b-while-integrating-vykat-xr"]]
    },
    {
      sym: "bme/AMS", code: "AMS", name: "Amadeus IT Group", market: "Europe", country: "Spain", sector: "Technology", t212: "AMSe_EQ", ccy: "EUR",
      flaggedDate: "2026-09-30", flaggedPrice: 52.02,
      thesis: "The software backbone of global air travel (airline reservation systems and the network travel agents book through), with 30% operating margins, priced at about 14× forward earnings against about 21× for European tech, and down 21% in a year. It trades in euros on Trading 212.",
      whyCheap: "The same AI fear as Booking, one layer deeper: if AI agents book directly with airlines, the distribution network that Amadeus charges a fee on could be bypassed. Growth has also slowed. H1 2026 revenue rose 5.1% at constant currency, air distribution only 1.1%, and in July management trimmed 2026 guidance to mid-to-high single-digit revenue growth because IATA cut its air-traffic forecast.",
      whyWrong: "Most of the growth is now outside distribution. Airline IT (the systems airlines run on) grew 8.7% and hotel software 9.2% in H1, and those are sticky, multi-year contracts that AI doesn't replace. Airlines still need a system to hold their inventory and prices, and AI agents need that data. EPS is still guided to grow high single to low double digits. Deutsche Bank upgraded it to Buy with a €71.50 target (about 37% above the flagged price).",
      bear: "If airlines push more sales to their own channels (as with the NDC standard) and AI agents speed that up, distribution fees shrink. Air travel is cyclical and exposed to oil and conflicts. Sabre is fighting harder for share. This overlaps with Booking: both are bets that AI fears in travel are overdone, so owning both would double that one bet.",
      watch: "Air distribution bookings growth vs airline IT growth: if IT keeps growing near 9%, the mix shift is working.",
      catalysts: [
        { d: "1–13 Oct 2026", e: "Update: Japan Airlines starts selling NDC tickets (the airline-controlled content standard) through Amadeus to agencies in 26 countries, from 1 Oct in Japan and 13 Oct overseas. That shows Amadeus can carry the 'direct' content that was supposed to bypass it. Shares are up about 2% since flagged after Deutsche Bank's upgrade", url: "https://www.ad-hoc-news.de/boerse/news/corporate-news/amadeus-and-jal-announce-ndc-sales-rollout-as-amadeus-it-group-stock-holds-at-eur-52-97/70220410" },
        { d: "6 Nov 2026", e: "Q3 2026 results", url: "https://www.tipranks.com/news/company-announcements/amadeus-sets-dates-for-2026-half-year-and-full-year-results" },
        { d: "Ongoing", e: "AI search tools for travel ('answer to AI's infinite search problem'): Amadeus positioning as the data layer for agents", url: "https://skift.com/2026/06/23/amadeus-has-an-answer-for-ais-infinite-search-problem/" },
        { d: "2026–27", e: "Competition with Sabre for airline and agency contracts", url: "https://skift.com/2026/05/11/amadeus-q1-2026-earnings-sabre-ai/" }
      ],
      videos: [["Amadeus jumps: Bloomberg Stock Movers (May 2026)", "https://www.youtube.com/watch?v=ZmPUwu7p5Sc"]],
      sources: [["Amadeus H1 2026 results", "https://amadeus.com/en/newsroom/press-releases/amadeus-h1-2026-resilient-performance"], ["Investing.com: margins outweigh trimmed 2026 outlook", "https://m.investing.com/news/earnings/amadeus-rises-as-strong-margins-outweigh-trimmed-2026-outlook-4826954?ampMode=1"], ["Heavy Moat Investments: is the moat crumbling?", "https://heavymoatinvestments.substack.com/p/amadeus-it-is-the-travel-infrastructure"]]
    },
    {
      sym: "CHKP", code: "CHKP", name: "Check Point Software", market: "US", country: "US (Israel company)", sector: "Technology", t212: "CHKP_US_EQ", ccy: "USD",
      flaggedDate: "2026-09-30", flaggedPrice: 126.93,
      thesis: "One of the oldest and most profitable cybersecurity companies (29% operating margin, 36% return on capital), down 38% in a year to about 12× forward earnings, half the tech-sector average, while management says product sales return to growth in Q4.",
      whyCheap: "Two stumbles this year. In Q1 it missed revenue, cut 2026 guidance and was downgraded by Piper Sandler; the stock fell over 19% in a day. In Q2 product revenue (firewall appliances) fell 14% as customers delayed big purchases, and the stock fell another 8%. A sales-force overhaul under CEO Nadav Zafrir disrupted execution, and investors see Check Point as a slow-growing legacy firewall company losing out to Palo Alto, CrowdStrike and Zscaler.",
      whyWrong: "The slowdown is concentrated in hardware timing, not demand. Subscriptions grew 12% to $333M in Q2, and newer products (email security, threat exposure management, AI security) are each growing 40%+. Q2 adjusted EPS of $2.55 beat estimates, and full-year guidance ($2.77–2.85B revenue, about $10.45 EPS) was kept. Zafrir has been buying AI-security companies (Lakera, about $300M, plus Cyata, Cyclops, Rotate and Deepchecks) to position Check Point for securing AI agents.",
      bear: "If Q4 firewall deals slip again, the 'delayed, not lost' story breaks and guidance falls. Cybersecurity is consolidating around platform players, and Check Point has been losing share for years. Acquisitions can distract a sales force already being rebuilt. Its growth has been single-digit for a decade, so a low multiple might simply be the right one.",
      watch: "Product revenue in Q4 (management says it turns positive) and subscription growth staying above 10%.",
      catalysts: [
        { d: "Sept 2026", e: "Update: removed from the FTSE All-World index in September, which forced index funds to sell. That's mechanical selling, not news about the business. Shares are up about 3% since flagged", url: "https://simplywall.st/stocks/us/software/nasdaq-chkp/check-point-software-technologies/news/will-index-removal-change-check-point-stock-narrative" },
        { d: "2 Nov 2026", e: "Q3 2026 results (confirmed; call at 8:30am ET): first check on the promised Q4 product rebound", url: "https://checkpoint.com/press-releases/check-point-software-to-announce-2026-third-quarter-financial-results-on-november-2-2026" },
        { d: "Q4 2026", e: "Delayed firewall appliance purchases expected to land", url: "https://siliconangle.com/2026/07/30/check-point-software-drops-8-mixed-second-quarter-results/" },
        { d: "Ongoing", e: "AI security push: Lakera, Deepchecks and more; CEO says to 'expect acquisitions to increase'", url: "https://www.calcalistech.com/ctechnews/article/byyttqa0xl" }
      ],
      videos: [["Check Point CEO Nadav Zafrir on the Nvidia partnership", "https://www.youtube.com/watch?v=bNpCcptQPHc"], ["The View from Davos with Check Point CEO Nadav Zafrir", "https://www.youtube.com/watch?v=rSsotqxn5pc"]],
      sources: [["SiliconANGLE: drops 8% on mixed Q2", "https://siliconangle.com/2026/07/30/check-point-software-drops-8-mixed-second-quarter-results/"], ["MarketScreener: guidance cut, Piper Sandler downgrade", "https://www.marketscreener.com/news/check-point-software-shares-decline-after-revenue-guidance-cut-piper-sandler-downgrade-ce7f58d8dc88f626"], ["Check Point Q2 2026 results", "https://www.checkpoint.com/press-releases/check-point-software-reports-2026-second-quarter-financial-results/"]]
    },
    {
      sym: "lon/IGG", code: "IGG", name: "IG Group", market: "UK", country: "UK", sector: "Financials", t212: "IGGl_EQ", ccy: "GBX",
      flaggedDate: "2026-10-05", flaggedPrice: 989,
      thesis: "The UK's biggest online trading platform (spread bets, CFDs and share dealing), with a 36% operating margin and net cash, at about 7.7× forward earnings with a near-5% dividend after two big one-day falls in ten weeks. It trades in pounds in London, so there's no FX fee.",
      whyCheap: "Two shocks. On 30 July IG agreed to buy Underdog, a US fantasy-sports and prediction-markets operator, for $1.1B upfront (up to $1.3B), funded partly by a bridge loan of up to $950M, and paused its £125M buyback after only £33M. The shares fell about 23%. Then on 2 Oct it warned that Q3 revenue would fall about 14% to roughly £240M because 'OTC revenue retention' (how much of clients' trading IG keeps as revenue) dropped to about 70% from around 80%. It cut 2026 growth guidance from 10–15% to mid-single digits and flagged £30M of one-off costs. The shares fell another 27%, to their lowest since April 2025.",
      whyWrong: "The Q3 miss is about retention, which swings with market conditions, rather than about losing customers: active customers rose about 17% and new first trades rose over 25%. Underdog was the third-largest US prediction-markets venue by regulated volume, with $466M of revenue in the year to June, and would more than double IG's US revenue. Even with lower growth, the business is very cash-generative (about a 33% free-cash-flow margin), and at under 8× earnings the market is pricing a lot of bad news at once.",
      bear: "Two nasty surprises in ten weeks damage management's credibility, and the forward P/E may not yet include the guidance cut, so it could be less cheap than it looks. Underdog is a big bet on a young US market whose regulation is still settling, and the deal turns net cash into debt. The buyback is paused until at least 2027. Retail CFD trading is a product most clients lose money on, which keeps regulators watching closely. This is a recovery idea straight after a profit warning, which is the riskiest point to research one.",
      watch: "OTC revenue retention getting back towards 80%, and the Underdog closing and regulatory approvals.",
      catalysts: [
        { d: "2 Oct 2026", e: "Q3 trading update: revenue about −14%, growth guidance cut to mid-single digits, EBITDA margin now low-40s%. Shares −27%", url: "https://www.investing.com/news/stock-market-news/ig-group-expects-q3-revenue-to-fall-14-as-otc-retention-weakens-4928936" },
        { d: "Late 2026–early 2027", e: "Underdog completion, subject to US antitrust (HSR) clearance and other approvals", url: "https://finance.yahoo.com/markets/stocks/articles/ig-group-acquire-underdog-1-190432369.html" },
        { d: "2027", e: "Possible restart of the paused buyback after the parent company moves its legal home to Jersey, 'subject to share-price performance'", url: "https://www.globalbankingandfinance.com/uks-ig-group-cuts-2026-revenue-outlook-weaker-otc-trading/" }
      ],
      videos: [["IG Group 2025 results presentation (CEO Breon Corcoran and CFO)", "https://www.youtube.com/watch?v=LStKe4RUUWA"]],
      sources: [["Investing.com: shares plunge 27% on weaker OTC retention", "https://www.investing.com/news/stock-market-news/ig-group-expects-q3-revenue-to-fall-14-as-otc-retention-weakens-4928936"], ["Reuters via TradingView: IG cuts 2026 revenue outlook", "https://www.tradingview.com/news/reuters.com,2026:newsml_L6N45O0AT:0-uk-s-ig-group-cuts-2026-revenue-outlook-on-weaker-otc-trading/"], ["iGB: IG's billion-dollar punt on Underdog", "https://igamingbusiness.com/strategy/ig-group-underdog-billion-dollar-punt-prediction-markets/"], ["Gaming Intelligence: deal terms and bridge loan", "https://www.gamingintelligence.com/finance/234229-ig-group-eyes-us-prediction-market-opportunity-with-1-1-billion-underdog-acquisition/"]]
    },
    {
      sym: "epa/IPN", code: "IPN", name: "Ipsen", market: "Europe", country: "France", sector: "Healthcare", t212: "IPNp_EQ", ccy: "EUR",
      flaggedDate: "2026-10-05", flaggedPrice: 140.3,
      thesis: "A French specialty drugmaker growing sales 23.5% (constant currency) with a 38.6% core margin and €1B of net cash, at under 10× forward earnings against about 16× for healthcare, because its biggest drug just got a US generic rival.",
      whyCheap: "Somatuline (used for neuroendocrine tumours and acromegaly) made about 30% of H1 2026 sales, with roughly $983M of US sales in the year to July. On 21 Sept the FDA approved Amneal's generic version, Amneal said it would launch immediately, and Ipsen fell about 7%. Analysts rate it Hold and see little upside. In July, a Phase III trial of Bylvay in biliary atresia also failed.",
      whyWrong: "Everything else is growing fast. Sales outside Somatuline rose 24.8% in H1. Iqirvo (a liver disease drug) roughly tripled to €173M, Bylvay grew 45% in its approved uses and Cabometyx 19%. Management raised 2026 guidance in July to over 20% sales growth and over 37% core margin. Two positive Phase III results should widen the market: Dysport became the first botulinum toxin to work in both episodic and chronic migraine, and Iqirvo's ELSPIRE study supports treating more patients. H1 free cash flow of €652M pays for new pipeline deals (Kartos, $450M upfront; Memo, €200M).",
      bear: "Generics can take share fast. Ipsen's guidance assumed Somatuline keeps growing despite a possible generic, so 2026–27 numbers may need cutting, and the low forward P/E may not fully include that. The stock is up about 18% in a year, so this is cheap on numbers rather than hated. The newly bought drugs are years from sales (navtemadlin data in 2027). It adds healthcare, alongside GSK and Neurocrine on this list.",
      watch: "Q3 sales on 22 Oct: Somatuline's US trend in the first weeks of generic competition, and whether management keeps the >20% guide.",
      catalysts: [
        { d: "22 Oct 2026", e: "Q3 and year-to-date sales update: first read on generic lanreotide's impact", url: "https://www.ipsen.com/wp-content/uploads/2026/07/Ipsen-PR_HY-2026_30072026.pdf" },
        { d: "2026–27", e: "Regulatory filings for Dysport in migraine and Iqirvo's wider PBC label", url: "https://www.ipsen.com/wp-content/uploads/2026/07/Ipsen-PR_HY-2026_30072026.pdf" },
        { d: "2027", e: "Navtemadlin (myelofibrosis) Phase III POIESIS topline, from the Kartos deal (up to $1.3B in milestones)", url: "https://www.ipsen.com/wp-content/uploads/2026/07/Ipsen-PR_HY-2026_30072026.pdf" },
        { d: "21 Sept 2026", e: "FDA approves Amneal's generic Somatuline; immediate launch; Ipsen −7%", url: "https://uk.investing.com/news/stock-market-news/ipsen-shares-fall-7-after-us-approval-of-generic-somatuline-rival-93CH-4875588" }
      ],
      videos: [["IMD CEO Dialogue #50: Ipsen CEO David Loew on the growth strategy", "https://www.youtube.com/watch?v=Lq_3nySt3Ro"]],
      sources: [["Ipsen H1 2026 results and upgraded guidance", "https://www.ipsen.com/wp-content/uploads/2026/07/Ipsen-PR_HY-2026_30072026.pdf"], ["Investing.com: shares fall 7% on US generic approval", "https://uk.investing.com/news/stock-market-news/ipsen-shares-fall-7-after-us-approval-of-generic-somatuline-rival-93CH-4875588"], ["TS2: Somatuline generic pulls 2027 risk forward", "https://ts2.tech/en/ipsen-shares-lose-7-as-somatuline-generic-pulls-2027-risk-forward/"]]
    },
    {
      sym: "CPRT", code: "CPRT", name: "Copart", market: "US", country: "US", sector: "Industrials", t212: "CPRT_US_EQ", ccy: "USD",
      flaggedDate: "2026-10-05", flaggedPrice: 27.22,
      thesis: "The dominant online auction for written-off cars (insurers sell total losses through it), with a 35% operating margin, 28% return on capital and about $4.4B of net cash with no debt, down about 40% in a year to about 17× forward earnings against roughly 23× for industrials. For years this was one of the market's most expensive 'compounders'.",
      whyCheap: "Fewer insured crashes are reaching it. US insurance volumes fell 8% in fiscal 2026 as drivers facing higher premiums drop collision cover or raise deductibles. Full-year revenue grew only 0.4% to $4.7B; Q4 net income fell 17% and cost per vehicle rose 12.7%. CEO Jeff Liaw left in July and founder-era CEO Jay Adair returned. HSBC downgraded it to Hold ($36), while rival RB Global grew auto volumes 11% in Q2. It hit a 52-week low of about $26.8 in late September.",
      whyWrong: "The volume drop looks cyclical (insurance got unaffordable) rather than structural. Cars are getting harder and costlier to repair ('computers on wheels'), which pushes total-loss frequency to records, and selling prices are still rising (+3.1% globally in Q4). International revenue grew about 12% and every overseas market is profitable. The $1.9B all-cash ACV Auctions deal takes it into dealer-to-dealer used-car sales, and it bought back about $1.6B of stock earlier in fiscal 2026. Adair says he isn't a stopgap and plans to stay 10+ years.",
      bear: "If US insurance volumes keep shrinking and RB Global keeps winning share, Copart is a no-growth company, and 17× earnings isn't cheap for that. ACV is a lower-margin business with integration risk. Rising cost per car is already squeezing margins. A stock that used to trade at a premium can stay re-rated lower for years.",
      watch: "US insurance unit volumes turning positive, and gross margin holding above about 42%.",
      catalysts: [
        { d: "~19 Nov 2026", e: "Q1 FY27 results (estimated date)", url: "https://finance.yahoo.com/markets/stocks/articles/copart-inc-cprt-q4-2026-090100470.html" },
        { d: "By end-2026", e: "ACV Auctions acquisition closes ($10.50 per share in cash, about $1.9B; tender offer under way)", url: "https://www.insurancejournal.com/news/east/2026/09/14/884939.htm" },
        { d: "Ongoing", e: "Insurance premiums: if premium inflation cools, more drivers keep collision cover and volumes recover", url: "https://www.investing.com/news/analyst-ratings/copart-stock-downgraded-by-hsbc-on-weak-insurance-volumes-93CH-4904840" }
      ],
      videos: [["Dying Compounder or Rare Discount? Copart Explained", "https://www.youtube.com/watch?v=Ar8QlzMhcfs"], ["Copart Stock (CPRT): Is Copart now a Buy?", "https://www.youtube.com/watch?v=2TenulJCKVQ"]],
      sources: [["Yahoo: Q4 FY2026 earnings call highlights", "https://finance.yahoo.com/markets/stocks/articles/copart-inc-cprt-q4-2026-090100470.html"], ["Insurance Journal: Copart to buy ACV for $1.9B", "https://www.insurancejournal.com/news/east/2026/09/14/884939.htm"], ["Investing.com: HSBC downgrade on weak insurance volumes", "https://www.investing.com/news/analyst-ratings/copart-stock-downgraded-by-hsbc-on-weak-insurance-volumes-93CH-4904840"], ["TIKR: surprise CEO change", "https://www.tikr.com/blog/copart-stock-fell-8-this-week-on-a-surprise-ceo-change-heres-where-the-stock-could-go-in-2026"]]
    }
  ]
};
